CREATE TABLE IF NOT EXISTS `character` (
  player_id INT NOT NULL,
  name VARCHAR(100) NOT NULL UNIQUE,
  exp INT DEFAULT 0,
  gold_amount INT DEFAULT 0,
  FOREIGN KEY (player_id) REFERENCES player(id) ON DELETE CASCADE
);